site_name: Documentação Kanbanda
site_url: https://ctism-prof-henry.github.io/software-formularios-kanbanda/
theme: readthedocs
nav:
  - Início: index.md
  - Instalação: instalacao.md
  - Permissões e Segurança: seguranca.md
  - URLs do Sistema: urls.md
markdown_extensions:
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
