# Generated by Django 4.2.30 on 2026-06-06 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizacional', 'initial_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDeRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sem_tratamento', 'Sem Tratamento'), ('com_tratamento', 'Com Tratamento')], db_index=True, default='sem_tratamento', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos_criados', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='organizacional.setor')),
            ],
            options={
                'verbose_name': 'Plano de Risco',
                'verbose_name_plural': 'Planos de Risco',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TratamentoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('EVITAR', 'Evitar'), ('ACEITAR', 'Aceitar')], max_length=15)),
                ('tipo_acao', models.CharField(choices=[('PREVENTIVA', 'Preventiva'), ('CORRETIVA', 'Corretiva'), ('COMPENSATORIA', 'Compensatória')], max_length=15)),
                ('descricao_acao', models.TextField(verbose_name='Descrição da Ação')),
                ('situacao', models.CharField(choices=[('NAO_INICIADO', 'Não Iniciado'), ('EM_EXECUCAO', 'Em Execução'), ('CONCLUIDO', 'Concluído'), ('ATRASADO', 'Atrasado')], default='NAO_INICIADO', max_length=15)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao_prevista', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=200)),
                ('parceiros', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('resultados_observados', models.TextField(blank=True)),
                ('analise_critica', models.TextField(blank=True)),
                ('plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamento', to='riscos.planoderisco')),
            ],
            options={
                'verbose_name': 'Tratamento do Risco',
            },
        ),
        migrations.CreateModel(
            name='IdentificacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(choices=[('ESTRATEGICO', 'Estratégico'), ('OPERACIONAL', 'Operacional'), ('INTEGRIDADE', 'Integridade'), ('IMAGEM', 'Imagem'), ('LEGAL', 'Legal / Conformidade'), ('FINANCEIRO', 'Financeiro / Orçamentário'), ('AMB_EXTERNO', 'Ambiente Externo')], max_length=20)),
                ('descricao_evento', models.TextField(verbose_name='Descrição do Evento de Risco')),
                ('causas', models.TextField(verbose_name='Causas')),
                ('consequencias', models.TextField(verbose_name='Conseqüências')),
                ('macroprocesso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao.macroprocesso')),
                ('objetivo_pdi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao.objetivopdi')),
                ('plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identificacao', to='riscos.planoderisco')),
            ],
            options={
                'verbose_name': 'Identificação do Risco',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlanoDeRisco',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('sem_tratamento', 'Sem Tratamento'), ('com_tratamento', 'Com Tratamento')], db_index=True, default='sem_tratamento', max_length=20)),
                ('criado_em', models.DateTimeField(blank=True, editable=False)),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizacional.setor')),
            ],
            options={
                'verbose_name': 'historical Plano de Risco',
                'verbose_name_plural': 'historical Planos de Risco',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AvaliacaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade', models.PositiveSmallIntegerField(choices=[(1, '1 — Muito Baixa'), (2, '2 — Baixa'), (3, '3 — Média'), (4, '4 — Alta'), (5, '5 — Muito Alta')])),
                ('impacto', models.PositiveSmallIntegerField(choices=[(1, '1 — Muito Baixo'), (2, '2 — Baixo'), (3, '3 — Médio'), (4, '4 — Alto'), (5, '5 — Muito Alto')])),
                ('risco_inerente', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('nivel_inerente', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('EXTREMO', 'Extremo')], editable=False, max_length=10)),
                ('eficacia_controles', models.CharField(choices=[('INEXISTENTE', 'Inexistente'), ('FRACO', 'Fraco'), ('MEDIANO', 'Mediano'), ('SATISFATORIO', 'Satisfatório'), ('FORTE', 'Forte')], max_length=15)),
                ('descricao_controles', models.TextField(blank=True, verbose_name='Descrição dos Controles Internos')),
                ('risco_residual', models.FloatField(default=0, editable=False)),
                ('nivel_residual', models.CharField(blank=True, choices=[('BAIXO', 'Baixo'), ('MODERADO', 'Moderado'), ('ALTO', 'Alto'), ('EXTREMO', 'Extremo')], editable=False, max_length=10)),
                ('plano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='riscos.planoderisco')),
            ],
            options={
                'verbose_name': 'Avaliação do Risco',
            },
        ),
    ]
