# Generated by Django 4.2.30 on 2026-06-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riscos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacaorisco',
            name='consequencias',
            field=models.TextField(verbose_name='Consequências'),
        ),
    ]
