# Generated by Django 4.2.30 on 2026-06-16 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
        ('riscos', '0003_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificacaorisco',
            name='desafio_pdi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracao.desafiopdi'),
        ),
    ]
