# Generated by Django 6.0.5 on 2026-05-11 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID do objeto')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo alterado')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor novo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_alteracao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Alteração',
                'verbose_name_plural': 'Logs de Alteração',
                'ordering': ['-criado_em'],
            },
        ),
    ]
