# Generated by Django 6.0.5 on 2026-05-11 11:56

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TentativaLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True, verbose_name='IP')),
                ('tentativas', models.PositiveSmallIntegerField(default=0, verbose_name='Tentativas')),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado até')),
                ('ultima_tentativa', models.DateTimeField(auto_now=True, verbose_name='Última tentativa')),
            ],
            options={
                'verbose_name': 'Tentativa de Login',
                'verbose_name_plural': 'Tentativas de Login',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('primeiro_nome', models.CharField(max_length=80, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('matricula', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail Institucional')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Institucional')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo / Função')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador do Sistema'), ('GESTOR_UNIDADE', 'Gestor da Unidade'), ('GESTOR_SETOR', 'Gestor de Setor'), ('SERVIDOR', 'Servidor / Colaborador')], db_index=True, default='SERVIDOR', max_length=20, verbose_name='Perfil')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('conta_ativada', models.BooleanField(default=False, verbose_name='Conta Ativada')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso Admin Django')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('ultimo_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Último Login')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['primeiro_nome', 'sobrenome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUsuario',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('primeiro_nome', models.CharField(max_length=80, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('matricula', models.CharField(db_index=True, max_length=20, verbose_name='Matrícula')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='E-mail Institucional')),
                ('foto', models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone Institucional')),
                ('cargo', models.CharField(blank=True, max_length=120, verbose_name='Cargo / Função')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador do Sistema'), ('GESTOR_UNIDADE', 'Gestor da Unidade'), ('GESTOR_SETOR', 'Gestor de Setor'), ('SERVIDOR', 'Servidor / Colaborador')], db_index=True, default='SERVIDOR', max_length=20, verbose_name='Perfil')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('conta_ativada', models.BooleanField(default=False, verbose_name='Conta Ativada')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acesso Admin Django')),
                ('criado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Excluído em')),
                ('history_change_reason', models.TextField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('criado_por', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Usuário',
                'verbose_name_plural': 'historical Usuários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LogAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN_OK', 'Login bem-sucedido'), ('LOGIN_FALHA', 'Tentativa de login falha'), ('LOGOUT', 'Logout'), ('ATIVACAO', 'Ativação de conta'), ('RECUPERACAO_SENHA', 'Recuperação de senha'), ('BLOQUEIO_IP', 'IP bloqueado por brute force'), ('SESSAO_EXPIRADA', 'Sessão expirada')], db_index=True, max_length=30, verbose_name='Tipo')),
                ('identificador_tentado', models.CharField(blank=True, max_length=200, verbose_name='Matrícula/E-mail tentado')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='Detalhes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_acesso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acesso',
                'verbose_name_plural': 'Logs de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TokenAtivacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_ativacao', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_ativacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Ativação',
                'verbose_name_plural': 'Tokens de Ativação',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TokenRecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('ip_solicitante', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_uso', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_recuperacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Recuperação de Senha',
                'verbose_name_plural': 'Tokens de Recuperação de Senha',
                'ordering': ['-criado_em'],
            },
        ),
    ]
