# pylint: disable=invalid-name
''' Generated by Django 4.2.30 on 2026-05-18 22:24'''

from django.db import migrations, models


class Migration(migrations.Migration):
    '''Migração para alterar o campo detalhes do modelo LogAcesso
    para permitir texto em branco.'''

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logacesso',
            name='detalhes',
            field=models.TextField(blank=True, verbose_name='Detalhes'),
        ),
    ]
