# Generated by Django 4.2.30 on 2026-06-05 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Desafio PDI',
                'verbose_name_plural': 'Desafios PDI',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ObjetivoPDI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='configuracao.desafiopdi')),
            ],
            options={
                'verbose_name': 'Objetivo PDI',
                'verbose_name_plural': 'Objetivos PDI',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Macroprocesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='macroprocessos', to='configuracao.desafiopdi')),
            ],
            options={
                'verbose_name': 'Macroprocesso',
                'verbose_name_plural': 'Macroprocessos',
                'ordering': ['nome'],
            },
        ),
    ]
